HW requirements. configure pom.xml and spring
Vadym-Ozi/Online-Book-store pull request #1
Opened 2024-07-03 17:11 UTC by Vadym-Ozi

2024-07-04 06:27 UTC, Elena-Bruyako requested changes
Let's check task description

create a Spring Boot project with pom.xml file with all required dependencies
add Book entity
add BookRepository
add BookService
configure database access
configure checkstyle
configure application.properties in the test/resources folder
configure CI (Continuous Integration)
configure GitHub git branch flow (see the Hint section below)

Remove all unnecessary entities

2024-07-04 06:27 UTC, Elena-Bruyako commented on src/main/java/example/model/Book.java
> +@Data
Don't use `@Data` for entities, it could cause some issues

2024-07-04 06:27 UTC, Elena-Bruyako commented on src/main/java/example/model/Book.java
> +    @NotNull
Redundant using both of annotations `@Column(nullable = false) and @NotNull`

2024-07-04 06:27 UTC, Elena-Bruyako commented on src/main/java/example/model/Book.java
> +    @NotNull
```suggestion
```

Check all fields

2024-07-04 06:27 UTC, Elena-Bruyako commented on src/main/java/example/repository/impl/BookRepositoryImpl.java
> +        return null;
You need to implement methods

2024-07-04 06:27 UTC, Elena-Bruyako commented on src/main/java/example/service/impl/BookServiceImpl.java
> +        return null;
You need to implement methods

2024-07-04 06:27 UTC, Elena-Bruyako commented on pom.xml
> +
remove blank lines

2024-07-07 15:31 UTC, Elena-Bruyako requested changes
See pr

2024-07-07 15:31 UTC, Elena-Bruyako commented on src/main/java/example/OnlineBookStoreApplication.java
> +                Book book1 = new Book();
```suggestion
                Book book = new Book();
```

2024-07-07 15:31 UTC, Elena-Bruyako commented on src/main/java/example/model/Book.java
>  @Entity
```suggestion
@Entity
@Getter
@Setter
```

2024-07-07 15:31 UTC, Elena-Bruyako commented on src/main/java/example/model/Book.java
> +    public String toString() {
remove

2024-07-07 15:31 UTC, Elena-Bruyako commented on src/main/java/example/repository/impl/BookRepositoryImpl.java
> +            throw new DataProcessingException("DB is empty. " + e.getMessage());
```suggestion
            throw new DataProcessingException("Can't find all books", e);
```

2024-07-07 15:31 UTC, Elena-Bruyako commented on src/main/java/example/repository/impl/BookRepositoryImpl.java
> +            throw new DataProcessingException("Book not added to db. " + book);
```suggestion
            throw new DataProcessingException("Can't add book: " + book);
```

2024-07-07 19:06 UTC, Elena-Bruyako approved these changes
well done

2024-07-09 13:00 UTC, MentorMateAcademy requested changes

2024-07-10 17:47 UTC, Elena-Bruyako approved these changes
Good job

2024-07-10 19:43 UTC, Elena-Bruyako requested changes
see pr

2024-07-10 19:43 UTC, Elena-Bruyako commented on src/main/java/example/controller/BookController.java
> +@RequestMapping(value = "/books")
```suggestion
@RequestMapping("/books")
```

2024-07-10 19:43 UTC, Elena-Bruyako commented on src/main/java/example/service/impl/BookServiceImpl.java
> +    public BookDto deleteById(Long id) {
```suggestion
    public void deleteById(Long id) {
```

2024-07-10 19:43 UTC, Elena-Bruyako commented on src/main/java/example/service/impl/BookServiceImpl.java
> +        bookRepository.deleteById(id);
leave just this

2024-07-11 09:18 UTC, Elena-Bruyako approved these changes
well done

2024-07-13 16:51 UTC, MentorMateAcademy requested changes

2024-07-13 16:51 UTC, MentorMateAcademy commented on src/main/java/example/repository/book/BookSpecificationBuilder.java
> +    private static final String priceKeyword = "price";
It`s constants?

2024-07-13 16:51 UTC, MentorMateAcademy commented on src/main/java/example/repository/book/PriceSpecificationProvider.java
> +    private static final String priceParameter = "price";
The same

2024-07-13 16:52 UTC, MentorMateAcademy requested changes

2024-07-13 16:52 UTC, MentorMateAcademy commented on pom.xml
> +            <version>${liquibase.version}</version>
Why do you have these changes here in this PR?

2024-07-14 19:06 UTC, Vadym-Ozi commented on pom.xml
> +            <version>${liquibase.version}</version>
I created a new branch and then merged it with the branch configure/project. So I think that's because of this.

2024-07-14 19:09 UTC, Vadym-Ozi commented on pom.xml
> +            <version>${liquibase.version}</version>
I merged it wrong a little because I do not have those annotations you mentioned. fixing now

2024-07-14 19:11 UTC, Vadym-Ozi commented on src/main/java/example/repository/book/BookSpecificationBuilder.java
> +    private static final String priceKeyword = "price";
Yes it is constants

2024-07-16 08:21 UTC, Elena-Bruyako approved these changes
well done

2024-07-19 12:39 UTC, closed without merging