Added Shopping cart feature. Possibility to add to the cart, update q…
Vadym-Ozi/Online-Book-store pull request #10
Opened 2024-08-12 17:45 UTC by Vadym-Ozi

…uantity of added item, Delete cart item.

2024-08-13 10:08 UTC, Elena-Bruyako requested changes
see comments

2024-08-13 10:08 UTC, Elena-Bruyako commented on src/main/java/example/controller/ShoppingCartController.java
> +    public CartItemDto addItemToShoppingCart(@RequestBody @Valid RequestCartItemDto cartItemDto) {
```suggestion
    public ShoppingRespondCartDto addItemToShoppingCart(Authentication authentication, @RequestBody @Valid RequestCartItemDto cartItemDto) {
```

2024-08-13 10:08 UTC, Elena-Bruyako commented on src/main/java/example/controller/ShoppingCartController.java
> +    public CartItemDto updateShoppingCart(@RequestBody @Valid RequestUpdateCartItemDto cartItemDto,
```suggestion
    public ShoppingRespondCartDto updateShoppingCart(@RequestBody @Valid RequestUpdateCartItemDto cartItemDto,
```

2024-08-13 10:08 UTC, Elena-Bruyako commented on src/main/java/example/controller/ShoppingCartController.java
> +@RestController
```suggestion
@RestController
@Validated
```
as you use Positive for Long id

2024-08-13 10:08 UTC, Elena-Bruyako commented on src/main/java/example/dto/cartItem/RequestCartItemDto.java
> +    @Positive
```suggestion
    @Positive
    @NotNull
```

2024-08-13 10:08 UTC, Elena-Bruyako commented on src/main/java/example/model/ShoppingCart.java
> +    @OneToMany(mappedBy = "shoppingCart", cascade = CascadeType.ALL)
```suggestion
    @OneToMany(mappedBy = "shoppingCart", cascade = CascadeType.ALL, orphanRemoval = true)
```

2024-08-13 10:08 UTC, Elena-Bruyako commented on src/main/java/example/model/ShoppingCart.java
> +    private Set<CartItem> cartItems;
```suggestion
    private Set<CartItem> cartItems = new HashSet<>();
```

2024-08-13 10:08 UTC, Elena-Bruyako commented on src/main/java/example/model/ShoppingCart.java
> +@SQLRestriction("is_Deleted=false")
```suggestion
@SQLRestriction("is_deleted=false")
```

2024-08-13 10:08 UTC, Elena-Bruyako commented on src/main/java/example/service/impl/CartItemServiceImpl.java
> +public class CartItemServiceImpl implements CartItemService {
This service is redundant, all logic related to Shop cart only and should be in ShopCartService

2024-08-13 10:08 UTC, Elena-Bruyako commented on src/main/java/example/controller/ShoppingCartController.java
> +        return cartItemService.addItemToCart(cartItemDto);
```suggestion
        User user = (User) authentication.getPrincipal();
        return cartItemService.addItemToCart(cartItemDto, user.getId());
```

2024-08-13 10:08 UTC, Elena-Bruyako commented on src/main/java/example/controller/ShoppingCartController.java
> +        return shoppingCartService.getShoppingCart();
```suggestion
    public ShoppingRespondCartDto getCurrentUserShoppingCart(Authentication authentication) {
        User user = (User) authentication.getPrincipal();
        return shoppingCartService.getShoppingCart(user.getId());
```

2024-08-13 10:08 UTC, Elena-Bruyako commented on src/main/java/example/controller/ShoppingCartController.java
> +        return cartItemService.updateCartItem(cartItemDto, cartItemId);
```suggestion
        return cartItemService.updateCartItem(cartItemDto, cartItemId, user.getId());
```

2024-08-13 10:08 UTC, Elena-Bruyako commented on src/main/java/example/controller/ShoppingCartController.java
> +        cartItemService.deleteCart(cartItemId);
```suggestion
        cartItemService.deleteCart(cartItemId, user.getId());
```

2024-08-13 10:08 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/10-create-cart-item-table.yaml
> +                  constraints:
foreignKey?

2024-08-13 10:08 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/10-create-cart-item-table.yaml
> +                  constraints:
foreignKey?

2024-08-13 10:08 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/09-create-shopping-cart-table.yaml
> +                  constraints:
foreignKey?

2024-08-14 12:08 UTC, Elena-Bruyako requested changes
see comments

2024-08-14 12:08 UTC, Elena-Bruyako commented on src/main/java/example/service/impl/ShoppingCartServiceImpl.java
> +    @Override
Add Transactional where is needed

2024-08-14 12:08 UTC, Elena-Bruyako commented on src/main/java/example/service/impl/ShoppingCartServiceImpl.java
> +        CartItem cartItem = findCartItem(cartItemId, userId);
Other option of implementation 
```
ShoppingCart cart = repository.findByUserId(userId);
CartItem cartItem = itemRepository.findByIdAndShoppingCartId(cartItemId, cart.getId())...
setQuantity
cartItemRepository.save(cartItem);
return shoppingCartMapper.toRespondDto(shoppingCart);
```

2024-08-14 12:08 UTC, Elena-Bruyako commented on src/main/java/example/service/impl/ShoppingCartServiceImpl.java
> +        ShoppingCart shoppingCart = shoppingCartRepository.findByUserId(userId);
Other option of implementation
```
Book book = bookRepository.findById(itemDto.bookId())...
ShoppingCart cart = repository.findByUserId(userId);
cart.getCartItems().stream() -> check if book already exists - increase quantity, if no - set book to cartItem and set cartItem to shop cart 
shoppingCartRepository.save(cart);
return shoppingCartMapper.toDto(cart);
```

2024-08-14 12:08 UTC, Elena-Bruyako commented on src/main/java/example/service/impl/ShoppingCartServiceImpl.java
> +    public CartItemDto addItemToCart(RequestCartItemDto cartItemDto, Long userId) {
```suggestion
    public ShoppingRespondCartDto addItemToCart(RequestCartItemDto cartItemDto, Long userId) {
```

2024-08-14 13:32 UTC, Vadym-Ozi commented on src/main/java/example/service/impl/ShoppingCartServiceImpl.java
> +        ShoppingCart shoppingCart = shoppingCartRepository.findByUserId(userId);
haven't thought that request already has a book id

2024-08-15 08:47 UTC, Elena-Bruyako approved these changes

2024-08-15 13:02 UTC, merged