Added CustomGlobalExceptionHandler class. Added validation for dto fi…
Vadym-Ozi/Online-Book-store pull request #3
Opened 2024-07-15 14:39 UTC by Vadym-Ozi

…elds(title, author, isbn, price).

2024-07-15 14:48 UTC, Elena-Bruyako requested changes
good job! Let's improve your solution!

2024-07-15 14:48 UTC, Elena-Bruyako commented on src/main/java/example/dto/CreateBookRequestDto.java
> +    @NotNull
```suggestion
    @NotBlank
```

for String
check other places

2024-07-15 14:48 UTC, Elena-Bruyako commented on src/main/java/example/controller/BookController.java
> +    public BookDto createBook(@RequestBody @Valid CreateBookRequestDto requestDto) {
add `@Valid` for search endpoint

2024-07-15 15:00 UTC, Vadym-Ozi commented on src/main/java/example/controller/BookController.java
> +    public BookDto createBook(@RequestBody @Valid CreateBookRequestDto requestDto) {
it is exist in this file

2024-07-16 07:29 UTC, Elena-Bruyako requested changes
See comments

2024-07-16 07:29 UTC, Elena-Bruyako commented on src/main/java/example/controller/BookController.java
> +    public BookDto createBook(@RequestBody @Valid CreateBookRequestDto requestDto) {
I didn't see the validation here
```
 @GetMapping("/search")
    public List<BookDto> search(BookSearchParameters params) {
        return bookService.search(params);
    }
```

2024-07-16 07:29 UTC, Elena-Bruyako commented on src/main/java/example/controller/BookController.java
> +    public BookDto createBook(@RequestBody @Valid CreateBookRequestDto requestDto) {
Also, you can add `@Positive` to `@PathVariable Long id` for required endpoints 
and `@Validated` under the controller

2024-07-17 13:42 UTC, Elena-Bruyako requested changes
see pr

2024-07-17 13:42 UTC, Elena-Bruyako commented on src/main/java/example/controller/BookController.java
> +    public List<BookDto> search(@Valid BookSearchParameters params, Pageable pageable) {
```suggestion
    public List<BookDto> search(@Valid BookSearchParameters params, @ParameterObject @PageableDefault Pageable pageable) {
```

2024-07-17 13:42 UTC, Elena-Bruyako commented on src/main/java/example/controller/BookController.java
> +    public BookDto getBookById(@PathVariable @Positive Long id) {
Add `@ParameterObject @PageableDefault Pageable pageable` to getAll endpoint

2024-07-17 14:01 UTC, Vadym-Ozi commented on src/main/java/example/controller/BookController.java
> +    public BookDto getBookById(@PathVariable @Positive Long id) {
These changes are in the next Pagination PR i did not merge it with this branch yet because it has not been approved yet.

2024-07-17 14:19 UTC, Vadym-Ozi commented on src/main/java/example/controller/BookController.java
> +    public BookDto getBookById(@PathVariable @Positive Long id) {
https://habr.com/ru/articles/658539/
Am I understanding correctly, is that why we need to use @ParameterObject

2024-07-17 14:44 UTC, Elena-Bruyako commented on src/main/java/example/controller/BookController.java
> +    public BookDto getBookById(@PathVariable @Positive Long id) {
correct

2024-07-17 14:45 UTC, Elena-Bruyako requested changes
see pr

2024-07-17 14:45 UTC, Elena-Bruyako commented on src/main/java/example/controller/BookController.java
> +    public List<BookDto> search(@Valid @ParameterObject @PageableDefault BookSearchParameters params, Pageable pageable) {
```suggestion
    public List<BookDto> search(@Valid BookSearchParameters params, @ParameterObject @PageableDefault Pageable pageable) {
```

2024-07-17 17:56 UTC, okuzan approved these changes

2024-07-19 12:39 UTC, closed without merging