Implemented User entente. Created required DTOs and mapper. Implement…
Vadym-Ozi/Online-Book-store pull request #5
Opened 2024-07-22 21:53 UTC by Vadym-Ozi

…ed AuthController. Added validation to the project. Used GlobalException handler for custom exceptions. Created annotations.

2024-07-23 07:44 UTC, Elena-Bruyako requested changes
Good job! Let's improve it

2024-07-23 07:44 UTC, Elena-Bruyako commented on src/main/java/example/dto/userDtos/UserResponseDto.java
> +    private String id;
UserResponseDto should constains such fields:
```
Long id,
String email,
String firstName,
String lastName,
String shippingAddress
```

2024-07-23 07:44 UTC, Elena-Bruyako commented on src/main/java/example/dto/userDtos/UserRegistrationRequestDto.java
> +@Data
Annotation `@Data` already includes `@Setter and @Getter`. Decide which annotations should be removed

2024-07-23 07:44 UTC, Elena-Bruyako commented on src/main/java/example/dto/userDtos/UserDto.java
> +public class UserDto {
Is is reponse or request? Where is it used?

2024-07-23 07:44 UTC, Elena-Bruyako commented on src/main/java/example/exception/CustomGlobalExceptionHandler.java
> +        return createBodyMessage(ex, HttpStatus.BAD_REQUEST);
```suggestion
        return createBodyMessage(ex, HttpStatus.CONFLICT);
```

2024-07-23 07:44 UTC, Elena-Bruyako commented on src/main/java/example/exception/CustomGlobalExceptionHandler.java
> +    @ExceptionHandler(DataProcessingException.class)
Where did you throw this exception?

2024-07-23 07:44 UTC, Elena-Bruyako commented on src/main/java/example/service/impl/UserServiceImpl.java
> +        return userMapper.toUserRespondDto(savedUser);
```suggestion
        userRepository.save(user);
        return userMapper.toUserRespondDto(user);
```

2024-07-23 07:44 UTC, Elena-Bruyako commented on src/main/java/example/service/impl/UserServiceImpl.java
> +    @Override
Should we use `@Transactional`?

2024-07-23 07:44 UTC, Elena-Bruyako commented on src/main/java/example/service/impl/UserServiceImpl.java
> +        if (userRepository.findByEmail(request.getEmail()).isPresent()) {
```suggestion
        if (userRepository.existsByEmail(request.getEmail())) {
```

It's better, to avoid calling isPresent()

2024-07-23 07:44 UTC, Elena-Bruyako commented on src/main/java/example/service/impl/UserServiceImpl.java
> +            throw new RegistrationException("This email is already used. Can`t register user");
add email to exception message

2024-07-23 07:44 UTC, Elena-Bruyako commented on src/main/java/example/validation/FieldMatchValidation.java
> +        Class<?> clazz = value.getClass();
```suggestion
        Object field = new BeanWrapperImpl(value).getPropertyValue(this.password);
        Object fieldMatch = new BeanWrapperImpl(value).getPropertyValue(this.repeatPassword);
        return Objects.equals(field, fieldMatch);

2024-07-24 12:03 UTC, Vadym-Ozi commented on src/main/java/example/exception/CustomGlobalExceptionHandler.java
> +    @ExceptionHandler(DataProcessingException.class)
emm, it was in repoImpl, but yeah.. fixed

2024-07-24 12:54 UTC, Vadym-Ozi commented on src/main/java/example/service/impl/UserServiceImpl.java
> +    @Override
yes it makes sense

2024-07-24 14:33 UTC, Elena-Bruyako approved these changes
Well done

2024-07-24 15:03 UTC, closed without merging