Added JWT support. Implemented login logic.
Vadym-Ozi/Online-Book-store pull request #7
Opened 2024-07-29 20:52 UTC by Vadym-Ozi

2024-07-30 11:19 UTC, Elena-Bruyako requested changes
see comments

2024-07-30 11:19 UTC, Elena-Bruyako commented on src/main/java/example/Application.java
> +//@PropertySource("classpath:application.properties")
remove comment

2024-07-30 11:19 UTC, Elena-Bruyako commented on src/main/java/example/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader("Authorization");
Use Spring constant AUTHORIZATION from HttpHeaders

2024-07-30 11:19 UTC, Elena-Bruyako commented on src/main/java/example/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
Create constant for "Bearer "

2024-07-30 11:19 UTC, Elena-Bruyako commented on src/main/java/example/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
use constant.length()

2024-07-30 11:19 UTC, Elena-Bruyako commented on src/test/java/example/ApplicationTests.java
> +    // Temporary solution until i learn SBoot Test
remove commented code

2024-07-30 11:19 UTC, Elena-Bruyako commented on src/main/java/example/controller/AuthenticationController.java
> +    @PostMapping("/login")
Add swagger annotations for endpoints

2024-07-30 11:19 UTC, Elena-Bruyako commented on src/main/java/example/security/JwtUtil.java
> +        {
```suggestion
        try {
```

2024-08-01 14:26 UTC, okuzan commented on src/main/java/example/security/JwtAuthenticationFilter.java
> +    private static final int SUBSTRING_INDEX = 7;
just use TOKEN_NAME.length()

2024-08-01 14:50 UTC, Vadym-Ozi commented on src/main/java/example/security/JwtAuthenticationFilter.java
> +    private static final int SUBSTRING_INDEX = 7;
just now realized

2024-08-03 15:53 UTC, merged