Category feature
Vadym-Ozi/Online-Book-store pull request #8
Opened 2024-08-02 19:57 UTC by Vadym-Ozi

2024-08-04 15:55 UTC, Elena-Bruyako requested changes
see comments

2024-08-04 15:55 UTC, Elena-Bruyako commented on src/main/java/example/controller/CategoryController.java
> +    public List<CategoryDto> getAll() {
Add Pageable

2024-08-04 15:55 UTC, Elena-Bruyako commented on src/main/java/example/controller/CategoryController.java
> +    public CategoryDto createCategory(@RequestBody @Valid CategoryDto categoryDto){
CategoryDto should include id in response
create CategoryRequestDto

2024-08-04 15:55 UTC, Elena-Bruyako commented on src/main/java/example/dto/category/CategoryDto.java
> +    @Pattern(regexp = "^[A-Z][a-z]*$")
NotBlank?

2024-08-04 15:55 UTC, Elena-Bruyako commented on src/main/java/example/mapper/BookMapper.java
> +    @EntityGraph(attributePaths = "categories")
Does this annotation work here?

2024-08-04 15:55 UTC, Elena-Bruyako commented on src/main/java/example/service/impl/CategoryServiceImpl.java
> +        return categoryMapper.toDto(categoryRepository.save(category));
```suggestion
        Category category = repository.findById(id)
                .orElseThrow(() .....
                ));
        mapper.updateCategoryFromDto(categoryDto, category);
        return mapper.toDto(repository.save(category));
```

2024-08-06 18:37 UTC, Vadym-Ozi commented on src/main/java/example/mapper/BookMapper.java
> +    @EntityGraph(attributePaths = "categories")
nope, i was searching for a solution and forget to delete this.
fixed

2024-08-07 13:26 UTC, Elena-Bruyako requested changes
see comments

2024-08-07 13:26 UTC, Elena-Bruyako commented on src/main/java/example/controller/CategoryController.java
> +    public CategoryDto createCategory(@RequestBody @Valid CategoryDto categoryDto){
```suggestion
    public CategoryDto createCategory(@RequestBody @Valid CategoryRequestDto categoryDto){
```

2024-08-07 13:26 UTC, Elena-Bruyako commented on src/main/java/example/controller/CategoryController.java
> +@RestController
```suggestion
@RestController
@Validated
```

if you use `@Posititve` for id

2024-08-07 13:26 UTC, Elena-Bruyako commented on src/main/java/example/mapper/BookMapper.java
> +    @EntityGraph(attributePaths = "categories")
The annotation is still here

2024-08-07 13:26 UTC, Elena-Bruyako commented on src/main/java/example/mapper/CategoryMapper.java
> +    }
```suggestion
    void updateCategoryFromDto(CategoryRequestDto categoryDto, @MappingTarget Category category);
```

2024-08-07 13:26 UTC, Elena-Bruyako commented on src/main/java/example/model/Category.java
> +@SQLRestriction("is_Deleted=false")
```suggestion
@SQLRestriction("is_deleted=false")
```

2024-08-07 13:26 UTC, Elena-Bruyako commented on src/main/java/example/repository/book/BookRepository.java
> +
```suggestion
```

2024-08-07 13:26 UTC, Elena-Bruyako commented on src/main/java/example/security/JwtAuthenticationFilter.java
>          String bearerToken = request.getHeader(HEADER);
```suggestion
        String bearerToken = request.getHeader(HttpHeaders.AUTHORIZATION);
```

2024-08-07 13:26 UTC, Elena-Bruyako commented on src/main/java/example/security/JwtAuthenticationFilter.java
>      private static final String HEADER = "Authorization";
```suggestion
```

2024-08-07 13:26 UTC, Elena-Bruyako commented on src/main/java/example/service/impl/CategoryServiceImpl.java
> +    @Transactional
```suggestion
```

2024-08-07 13:26 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/04-create-users-roles-table.yaml
> +      id: create-users-roles-table.yaml
Why do you need yaml here?

2024-08-07 13:26 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/06-insert-books.yaml
> +      id: insert-books.yaml
same

2024-08-07 13:26 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/05-insert-data-to-db.yaml
> +      id: insert-data-to-db.yaml
same

2024-08-09 07:58 UTC, Elena-Bruyako approved these changes
good job

2024-08-12 18:06 UTC, closed without merging